create type project_status as enum ('ongoing', 'closed');
create type evidence_type as enum ('tax_invoice', 'cash_receipt', 'ocr_receipt', 'simple_receipt');
create type source_system as enum ('hometax', 'ocr', 'bank_csv', 'manual');
create type evidence_status as enum ('collected', 'needs_review', 'reviewed', 'matched');
create type match_status as enum ('matched', 'possible_match', 'unmatched', 'rejected');
create type review_action_type as enum ('approve', 'reject', 'manual_link');

create table if not exists projects (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  start_date date,
  end_date date,
  manager_name text,
  status project_status not null default 'ongoing',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists vendors (
  id bigint generated by default as identity primary key,
  name text not null,
  alias text,
  business_number text,
  created_at timestamptz not null default now()
);

create table if not exists evidences (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projects(id) on delete cascade,
  vendor_id bigint references vendors(id) on delete set null,
  vendor_name text not null,
  issue_date date not null,
  amount_supply numeric(15,2) not null default 0,
  amount_vat numeric(15,2) not null default 0,
  amount_total numeric(15,2) not null,
  payment_method text,
  evidence_type evidence_type not null,
  source_system source_system not null,
  status evidence_status not null default 'collected',
  ocr_confidence numeric(5,4),
  needs_review boolean not null default false,
  raw_payload jsonb,
  image_path text,
  created_at timestamptz not null default now()
);

create table if not exists bank_transactions (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projects(id) on delete cascade,
  transfer_date date not null,
  vendor_name text not null,
  description text,
  amount numeric(15,2) not null,
  account_number_masked text,
  source_system source_system not null default 'bank_csv',
  created_at timestamptz not null default now()
);

create table if not exists evidence_matches (
  id bigint generated by default as identity primary key,
  evidence_id bigint not null references evidences(id) on delete cascade,
  bank_transaction_id bigint not null references bank_transactions(id) on delete cascade,
  match_status match_status not null,
  score numeric(6,4) not null default 0,
  reason text,
  reviewed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists review_actions (
  id bigint generated by default as identity primary key,
  evidence_match_id bigint not null references evidence_matches(id) on delete cascade,
  action_type review_action_type not null,
  actor_name text not null,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists idx_projects_code on projects(code);
create index if not exists idx_projects_status on projects(status);
create index if not exists idx_vendors_name on vendors(name);
create index if not exists idx_vendors_alias on vendors(alias);
create index if not exists idx_evidences_project_id on evidences(project_id);
create index if not exists idx_evidences_vendor_name on evidences(vendor_name);
create index if not exists idx_evidences_issue_date on evidences(issue_date);
create index if not exists idx_evidences_status on evidences(status);
create index if not exists idx_bank_transactions_project_id on bank_transactions(project_id);
create index if not exists idx_bank_transactions_transfer_date on bank_transactions(transfer_date);
create index if not exists idx_evidence_matches_evidence_id on evidence_matches(evidence_id);
create index if not exists idx_evidence_matches_bank_tx_id on evidence_matches(bank_transaction_id);
create index if not exists idx_evidence_matches_status on evidence_matches(match_status);
